In [1]:
import numpy as np

#create array , matrix

Array

In [2]:
a=np.array([1,2,4])
print(a)

[1 2 4]


marix

In [4]:
b= np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


#shape  size of list or matrix

In [5]:
print(a.shape ,b.shape)

(3,) (2, 2)


In [8]:
#reshape 
c=a.reshape((3,1))
print(c)
c.shape

[[1]
 [2]
 [4]]


(3, 1)

multiply of d items must be == number of a array =>
3x1x1== count of([1,2,4])

In [11]:
d=a.reshape(3,1,-1)
d.shape

(3, 1, 1)

In [14]:
#concat
a1=np.array([1,2,3])
a2=np.array([4,6])
aSum=np.concatenate((a1,a2))
print(aSum)

[1 2 3 4 6]
