## Working With Numpy Package

In [4]:
import numpy as np

#create array , matrix

Array

In [5]:
a=np.array([1,2,4])
print(a)

[1 2 4]


marix

In [4]:
b= np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


#shape  size of list or matrix

In [5]:
print(a.shape ,b.shape)

(3,) (2, 2)


In [8]:
#reshape 
c=a.reshape((3,1))
print(c)
c.shape

[[1]
 [2]
 [4]]


(3, 1)

multiply of d items must be == number of a array =>
3x1x1== count of([1,2,4])

In [11]:
d=a.reshape(3,1,-1)
d.shape

(3, 1, 1)

In [14]:
#concat
a1=np.array([1,2,3])
a2=np.array([4,6])
aSum=np.concatenate((a1,a2))
print(aSum)

[1 2 3 4 6]


Data Broadcasting


In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c =a*b
c

array([ 4, 10, 18])

In [20]:
c=np.array([4])
d=a+c
d

array([5, 6, 7])

In [21]:
e= a+10
e

array([11, 12, 13])

#### select part of an Array

In [6]:
a=np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [7]:
b=a[2:7] # numbers are index of start 2=>3 and 7=>7 [,)
b

array([3, 4, 5, 6, 7])

In [8]:
b=a[2:7:2] #3rd number is the step => 2n
b

array([3, 5, 7])

In [9]:
c= a[a>3]
c

array([4, 5, 6, 7, 8])

In [10]:
sum_a =np.sum(a)
sum_a

36

In [11]:
max_a=np.max(a) #or min
max_a

8

In [12]:
a= np.array([4,2,6,1,89,1])
c=np.sort(a)
c

array([ 1,  1,  2,  4,  6, 89])

Generate a random Matrix 
np.random.randint(start,end,size)

In [13]:
a=np.random.randint(0,10,(3,4))
a

array([[6, 2, 4, 9],
       [2, 4, 6, 2],
       [8, 4, 1, 8]])

In [14]:
a=np.array([1,2,3]) #v vertical stack
b=np.array([4,5,6])
c=np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a=np.array([1,2,3]) #h horizontal stack
b=np.array([4,5,6])
c=np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

#### Data Normalization 

it means shifting avg to 0 and Std to 1

np.mean(list) # average of a list

In [18]:
mean_a=np.mean(a)
mean_a

2.0

In [19]:
std = np.std(a) # enheraf az meyar
std

0.816496580927726

In [20]:
norm_a =(a-mean_a)/std # avg =0 and std =1
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [23]:
a=np.mean(norm_a)
b=np.std(norm_a)
a,b

(0.0, 0.9999999999999999)